BEGIN;

CREATE TABLE IF NOT EXISTS terminology (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  term TEXT NOT NULL UNIQUE,
  explanation TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_mechanic (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  term TEXT NOT NULL,
  description TEXT NOT NULL,
  version_originated_in TEXT
);

COMMIT;
