CREATE TABLE IF NOT EXISTS incidents (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  severity TEXT NOT NULL,
  started_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  platforms TEXT NOT NULL DEFAULT '[]',
  regions TEXT NOT NULL DEFAULT '[]',
  services TEXT NOT NULL DEFAULT '[]',
  symptoms TEXT NOT NULL,
  summary TEXT NOT NULL,
  category TEXT,
  keywords TEXT NOT NULL DEFAULT '[]',
  impact TEXT,
  understanding TEXT,
  guidance TEXT,
  workaround TEXT,
  resolution TEXT,
  approved_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_severity ON incidents(severity);
CREATE INDEX IF NOT EXISTS idx_incidents_updated_at ON incidents(updated_at);

INSERT OR IGNORE INTO incidents (
  id, title, status, severity, started_at, updated_at, platforms, regions,
  services, symptoms, summary, category, keywords, impact, guidance,
  approved_message
) VALUES
  ('INC-001', 'Players Unable to Log In', 'active', 'critical',
   '2026-07-11T08:00:00.000Z', '2026-07-11T09:00:00.000Z',
   '["PC"]', '["Southeast Asia"]', '["authentication"]',
   'Players receive an authentication error when attempting to log in.',
   'Authentication errors prevent account access during peak hours.',
   'Authentication', '["login","authentication","error","account access"]',
   'Affected players cannot access the game.',
   'Advise players not to reset passwords while the incident is active.',
   'We are investigating login failures affecting players in Southeast Asia.'),
  ('INC-002', 'Missing Purchased Items', 'active', 'high',
   '2026-07-11T08:10:00.000Z', '2026-07-11T09:10:00.000Z',
   '["Mobile"]', '["Global"]', '["store","inventory"]',
   'Completed purchases do not appear in player inventories.',
   'Some purchased items are delayed after successful payment.',
   'Payment', '["purchase","payment","missing item","inventory"]',
   'Players are charged but cannot use the purchased items.',
   'Do not ask players to repeat the purchase; collect the transaction ID.',
   'We are investigating delayed delivery of purchased items.'),
  ('INC-003', 'High Matchmaking Latency', 'monitoring', 'medium',
   '2026-07-11T08:20:00.000Z', '2026-07-11T09:20:00.000Z',
   '["PC"]', '["Asia"]', '["matchmaking"]',
   'Ranked matchmaking takes longer and matches have increased latency.',
   'Players in Asia may experience matchmaking delay and lag.',
   'Performance', '["matchmaking","latency","lag","ranked match"]',
   'Ranked match quality and queue times are degraded.',
   'Advise players to retry after a short delay.',
   'We are monitoring elevated matchmaking latency in Asia.'),
  ('INC-004', 'Game Crashes After Latest Update', 'active', 'high',
   '2026-07-11T08:30:00.000Z', '2026-07-11T09:30:00.000Z',
   '["Android"]', '["Global"]', '["game client"]',
   'The game crashes during startup after installing the latest update.',
   'Some Android devices cannot launch the updated game client.',
   'Crash', '["crash","startup","update","android"]',
   'Affected Android players cannot start the game.',
   'Advise players not to reinstall repeatedly while the fix is prepared.',
   'We are investigating startup crashes on Android after the latest update.'),
  ('INC-005', 'Incorrect Ranked Rewards', 'active', 'medium',
   '2026-07-11T08:40:00.000Z', '2026-07-11T09:40:00.000Z',
   '["PC"]', '["Europe"]', '["ranked rewards"]',
   'Players receive rewards for a different rank after the season ends.',
   'Some competitive season rewards were calculated incorrectly.',
   'Rewards', '["ranked","rewards","season","incorrect reward"]',
   'Affected players have incorrect seasonal rewards.',
   'Ask players to retain screenshots of their final rank and rewards.',
   'We are reviewing incorrect ranked rewards from the completed season.');
